# Generated by Django 3.0.8 on 2020-08-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200828_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follows',
            new_name='following',
        ),
    ]
